repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      python_version: python3.6
      exclude: ^(conf|setup)\.py$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.1-1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: flake8
      exclude: ^(conf|setup)\.py$
-   repo: local
    hooks:
    - id: mypy
      name: mypy
      language: system
      entry: mypy
      files: ^.*\.py$
      exclude: ^(conf|setup)\.py$
